mailer:
  address: <%= ENV['MAILGUN_SMTP_SERVER'] || 'localhost' %>
  domain: <%= ENV['MAILER_DOMAIN'] || 'gmail.com' %>
  host: <%= ENV['HEROKU_APP_NAME'] ? "#{ENV['HEROKU_APP_NAME']}.herokuapp.com" : 'localhost' %>
  user_name: <%= ENV['MAILGUN_SMTP_LOGIN'] %>
  password: <%= ENV['MAILGUN_SMTP_PASSWORD'] %>
  port: <%= ENV['MAILGUN_SMTP_PORT'] || 1025 %>

mail_send_recipient: <%= ENV['MAIL_SEND_RECEPIENT'] %>
mail_stubbed_recipient: <%= ENV['MAIL_STUBBED_RECEPIENT'] %>
mailer_sender: <%= ENV['MAIL_SENDER'] || 'sender@example.com' %>
cache_expires_in: <%= ENV['CACHE_EXPIRES_IN'] || 43200 %>